-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

DROP EXTENSION pg_net;

ALTER TABLE public.staff
  ALTER COLUMN assigned_class DROP DEFAULT;

ALTER TABLE public.staff
  DROP COLUMN created_at;

ALTER TABLE public.staff
  ALTER COLUMN name DROP DEFAULT;

ALTER TABLE public.students
  DROP COLUMN created_at;

ALTER TABLE public.students
  ALTER COLUMN pin DROP DEFAULT;

ALTER TABLE public.activity_logs
  DROP CONSTRAINT activity_logs_meal_check;

ALTER TABLE public.activity_logs
  DROP CONSTRAINT activity_logs_mood_check;

ALTER TABLE public.activity_logs
  DROP CONSTRAINT activity_logs_nap_check;

ALTER TABLE public.activity_logs
  DROP CONSTRAINT activity_logs_staff_id_fkey;

ALTER TABLE public.activity_logs
  DROP COLUMN staff_id;

ALTER TABLE public.activity_logs
  DROP CONSTRAINT activity_logs_student_id_fkey;

ALTER TABLE public.students
  DROP CONSTRAINT students_class_check;

ALTER TABLE public.students
  DROP CONSTRAINT students_roll_number_key;

DROP INDEX public.idx_activity_logs_student_date;

ALTER TABLE public.activity_logs
  ALTER COLUMN student_id TYPE text USING student_id::text;

DROP INDEX public.idx_students_class;

DROP INDEX public.idx_students_roll;

ALTER TABLE public.students
  ALTER COLUMN roll_number TYPE text USING roll_number::text;

DROP POLICY anon_delete_activity_logs ON public.activity_logs;

DROP POLICY anon_insert_activity_logs ON public.activity_logs;

DROP POLICY anon_read_activity_logs ON public.activity_logs;

DROP POLICY anon_update_activity_logs ON public.activity_logs;

ALTER PUBLICATION supabase_realtime ADD TABLE public.activity_logs, TABLE public.daily_logs, TABLE public.gate_passes, TABLE public.students;

CREATE EXTENSION pg_cron WITH SCHEMA pg_catalog;

CREATE EXTENSION pg_net WITH SCHEMA public;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT DELETE, INSERT, SELECT, UPDATE ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT, USAGE ON SEQUENCES TO service_role;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO service_role;

ALTER TABLE public.staff
  ALTER COLUMN password SET NOT NULL;

ALTER TABLE public.students
  ALTER COLUMN class_name SET NOT NULL;

ALTER TABLE public.students
  ALTER COLUMN roll_no SET NOT NULL;

CREATE TABLE public."photo storage bucket" (
  id         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public."photo storage bucket"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."photo storage bucket"
  ADD CONSTRAINT "photo storage bucket_pkey" PRIMARY KEY (id);

GRANT ALL ON public."photo storage bucket" TO anon;

GRANT ALL ON public."photo storage bucket" TO authenticated;

GRANT ALL ON public."photo storage bucket" TO service_role;

ALTER TABLE public.activity_logs
  ADD COLUMN meal_status text;

ALTER TABLE public.activity_logs
  ADD COLUMN nap_time text;

ALTER TABLE public.activity_logs
  ADD COLUMN teacher_notes text;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.activity_logs TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.activity_logs TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.activity_logs TO service_role;

CREATE POLICY anon_all_activity_logs ON public.activity_logs
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

ALTER TABLE public.announcement_replies
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.announcement_replies TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.announcement_replies TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.announcement_replies TO service_role;

CREATE POLICY "public read ann_replies" ON public.announcement_replies
  FOR SELECT
  USING (true);

CREATE POLICY "public write ann_replies" ON public.announcement_replies
  FOR INSERT
  WITH CHECK (true);

ALTER TABLE public.announcements
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.announcements TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.announcements TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.announcements TO service_role;

CREATE POLICY "public read announcements" ON public.announcements
  FOR SELECT
  USING (true);

CREATE POLICY "public write announcements" ON public.announcements
  FOR INSERT
  WITH CHECK (true);

ALTER TABLE public.attendance
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.attendance TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.attendance TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.attendance TO service_role;

CREATE POLICY "Allow all access to attendance" ON public.attendance
  USING (true)
  WITH CHECK (true);

ALTER TABLE public.classwork
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.classwork TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.classwork TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.classwork TO service_role;

CREATE POLICY "Allow all access to classwork" ON public.classwork
  USING (true)
  WITH CHECK (true);

ALTER TABLE public.daily_grades
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.daily_grades TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.daily_grades TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.daily_grades TO service_role;

CREATE POLICY "Allow all access to daily_grades" ON public.daily_grades
  USING (true)
  WITH CHECK (true);

GRANT DELETE, INSERT, SELECT, UPDATE ON public.daily_logs TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.daily_logs TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.daily_logs TO service_role;

CREATE POLICY "Allow public access to daily_logs" ON public.daily_logs
  USING (true)
  WITH CHECK (true);

CREATE POLICY anon_all_daily_logs ON public.daily_logs
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

GRANT DELETE, INSERT, SELECT, UPDATE ON public.gate_passes TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.gate_passes TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.gate_passes TO service_role;

ALTER TABLE public.homework
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.homework TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.homework TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.homework TO service_role;

CREATE POLICY "public read homework" ON public.homework
  FOR SELECT
  USING (true);

CREATE POLICY "public write homework" ON public.homework
  FOR INSERT
  WITH CHECK (true);

ALTER TABLE public.homework_completions
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.homework_completions TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.homework_completions TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.homework_completions TO service_role;

ALTER TABLE public.homework_replies
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.homework_replies TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.homework_replies TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.homework_replies TO service_role;

CREATE POLICY "public read hw_replies" ON public.homework_replies
  FOR SELECT
  USING (true);

CREATE POLICY "public write hw_replies" ON public.homework_replies
  FOR INSERT
  WITH CHECK (true);

ALTER TABLE public.push_subscriptions
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.push_subscriptions TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.push_subscriptions TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.push_subscriptions TO service_role;

ALTER TABLE public.school_events
  ENABLE ROW LEVEL SECURITY;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.school_events TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.school_events TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.school_events TO service_role;

CREATE POLICY "public read events" ON public.school_events
  FOR SELECT
  USING (true);

CREATE POLICY "public write events" ON public.school_events
  FOR INSERT
  WITH CHECK (true);

GRANT DELETE, INSERT, SELECT, UPDATE ON public.staff TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.staff TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.staff TO service_role;

CREATE POLICY "Allow public access to staff" ON public.staff
  USING (true)
  WITH CHECK (true);

ALTER TABLE public.students
  ADD CONSTRAINT students_roll_no_key UNIQUE (roll_no);

GRANT DELETE, INSERT, SELECT, UPDATE ON public.students TO anon;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.students TO authenticated;

GRANT DELETE, INSERT, SELECT, UPDATE ON public.students TO service_role;

CREATE POLICY "Allow public access to students" ON public.students
  USING (true)
  WITH CHECK (true);
